name: Build & Deploy Locally

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        shell: cmd
        run: docker build -t flask-app-ci-test:latest .

      - name: Stop old container (if exists)
        shell: cmd
        continue-on-error: true
        run: docker stop flask-app

      - name: Remove old container (if exists)
        shell: cmd
        continue-on-error: true
        run: docker rm flask-app

      - name: Run updated container
        shell: cmd
        run: docker run -d --name flask-app -p 5000:5000 flask-app-ci-test:latest
